version: "3"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes

  web:
    build: .
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && ./bin/server"
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=postgres"
      - "REDIS_URL=redis://redis:6379"
    volumes:
      - ".:/app"
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
